# Generated by Django 2.0 on 2017-12-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20171220_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='by_first_layer',
            field=models.BooleanField(editable=False),
        ),
    ]
